// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSr3z9gnUPGZPEig68LCsmvgEPU9-77aU',
    appId: '1:915451905241:web:ea8e293a6baa91d84beac8',
    messagingSenderId: '915451905241',
    projectId: 'jaramarket-user',
    authDomain: 'jaramarket-user.firebaseapp.com',
    storageBucket: 'jaramarket-user.firebasestorage.app',
    measurementId: 'G-XQNR3QZZYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunotjL1sQUJXWSUIiDRFFeSeUsOiNsIQ',
    appId: '1:915451905241:android:9ea414b610a96ba24beac8',
    messagingSenderId: '915451905241',
    projectId: 'jaramarket-user',
    storageBucket: 'jaramarket-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7ypxWHlCGyBl8R-uyzPkoq90eAlteMY',
    appId: '1:915451905241:ios:b5f152fcb3371b3d4beac8',
    messagingSenderId: '915451905241',
    projectId: 'jaramarket-user',
    storageBucket: 'jaramarket-user.firebasestorage.app',
    androidClientId: '915451905241-bm4iespv811qjvlqb7qdib2fttrgtvet.apps.googleusercontent.com',
    iosClientId: '915451905241-d7rd39jm18lrjpqekunvd6ro0ciftfu0.apps.googleusercontent.com',
    iosBundleId: 'com.jaramarket.customer',
  );

}